/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PharmacyPackage;

/**
 * Pharmacy Management System - Medicine Inventory Form
 * This form allows users to add, view, and manage medicines in the pharmacy system.
 *
 * @author joopa04
 */
public class PharmacyForm extends javax.swing.JFrame {

    private final java.util.ArrayList<Medicine> medicineList =
            new java.util.ArrayList<Medicine>();

    private javax.swing.table.DefaultTableModel tableModel;

    /**
     * Creates new form PharmacyForm
     */
    public PharmacyForm() {
        initComponents();
        initializeTableModel();
        setLocationRelativeTo(null);
    }

    /**
     * Initialize the table model with proper configuration
     */
    private void initializeTableModel() {
        tableModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"#", "Generic Name", "Brand Name", "Description", "Dosage (mg)"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        medicineTable.setModel(tableModel);

        // Set column widths for better visibility
        medicineTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        medicineTable.getColumnModel().getColumn(1).setPreferredWidth(130);
        medicineTable.getColumnModel().getColumn(2).setPreferredWidth(130);
        medicineTable.getColumnModel().getColumn(3).setPreferredWidth(220);
        medicineTable.getColumnModel().getColumn(4).setPreferredWidth(90);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        programLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblGeneric = new javax.swing.JLabel();
        txtGeneric = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        lblMg = new javax.swing.JLabel();
        txtMg = new javax.swing.JTextField();
        btnPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        medicineTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Pharmacy — Medicine List");

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setLayout(new java.awt.BorderLayout(10, 10));

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        programLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        programLabel.setForeground(new java.awt.Color(153, 0, 255));
        programLabel.setText("-- Lejuene's Pharmacy --");
        titlePanel.add(programLabel);
        programLabel.getAccessibleContext().setAccessibleName("titleLabel");

        mainPanel.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Medicine"));
        formPanel.setMinimumSize(new java.awt.Dimension(200, 500));
        formPanel.setName(""); // NOI18N
        formPanel.setPreferredSize(new java.awt.Dimension(350, 300));
        formPanel.setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(30, 80, 160));
        lblTitle.setText("Pharmacy Entry Form");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(lblTitle, gridBagConstraints);

        lblGeneric.setText("Generic Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(lblGeneric, gridBagConstraints);

        txtGeneric.setColumns(15);
        txtGeneric.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(txtGeneric, gridBagConstraints);

        lblBrand.setText("Brand Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(lblBrand, gridBagConstraints);

        txtBrand.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(txtBrand, gridBagConstraints);

        lblDesc.setText("Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(lblDesc, gridBagConstraints);

        txtDesc.setColumns(15);
        txtDesc.setToolTipText("");
        txtDesc.setMinimumSize(new java.awt.Dimension(50, 22));
        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(txtDesc, gridBagConstraints);

        lblMg.setText("Dosage (mg):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(lblMg, gridBagConstraints);

        txtMg.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(txtMg, gridBagConstraints);

        btnPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));

        btnAdd.setBackground(new java.awt.Color(30, 120, 200));
        btnAdd.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Medicine");
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnPanel.add(btnAdd);

        btnClear.setBackground(new java.awt.Color(180, 50, 50));
        btnClear.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setFocusPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnPanel.add(btnClear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        formPanel.add(btnPanel, gridBagConstraints);

        mainPanel.add(formPanel, java.awt.BorderLayout.LINE_END);

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicine List"));

        medicineTable.setBackground(new java.awt.Color(255, 255, 255));
        medicineTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        medicineTable.setRowHeight(24);
        medicineTable.setSelectionBackground(new java.awt.Color(180, 210, 255));
        scrollPane.setViewportView(medicineTable);

        mainPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addMedicine();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void addMedicine() {
        String generic = txtGeneric.getText().trim();
        String brand   = txtBrand.getText().trim();
        String desc    = txtDesc.getText().trim();
        String mgText  = txtMg.getText().trim();

        if (generic.isEmpty() || brand.isEmpty() || desc.isEmpty() || mgText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "All fields are required.", "Input Error",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double mgValue;
        try {
            mgValue = Double.parseDouble(mgText);
            if (mgValue <= 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Dosage (mg) must be a valid positive number.", "Input Error",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Medicine m = new Medicine(generic, brand, desc, mgValue);
        medicineList.add(m);
        tableModel.addRow(new Object[]{
            medicineList.size(),
            m.getGenericName(),
            m.getBrandName(),
            m.getDescription(),
            String.format("%.1f", m.getMg())
        });

        clearFields();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Medicine \"" + brand + "\" added successfully.", "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void clearFields() {
        txtGeneric.setText("");
        txtBrand.setText("");
        txtDesc.setText("");
        txtMg.setText("");
        txtGeneric.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblGeneric;
    private javax.swing.JLabel lblMg;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable medicineTable;
    private javax.swing.JLabel programLabel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtGeneric;
    private javax.swing.JTextField txtMg;
    // End of variables declaration//GEN-END:variables
}
